Repository lf-lang/rust-rti, pull requests merged in 2024-03, with the labels that each got.

#45 Increase CI running time to pass more tests
  .github/workflows/rust.yml
Labels: ready, ci

#44 Enable log tracing information for RTI
  rust/rti/Cargo.toml
  rust/rti/src/lib.rs
  rust/rti/src/rti_common.rs
  rust/rti/src/server.rs
  rust/rti/src/tag.rs
  rust/rti/src/trace.rs
Labels: ready, feature

#46 Removed message_record, replace with in_transit_message_queue
  rust/.gitignore
  rust/rti/src/federate_info.rs
  rust/rti/src/in_transit_message_queue.rs
  rust/rti/src/lib.rs
  rust/rti/src/message_record/message_record.rs
  rust/rti/src/message_record/rti_pqueue_support.rs
  rust/rti/src/server.rs
Labels: enhancement, ready

#24 Adding basic unit tests
  rust/rti/Cargo.toml
  rust/rti/src/federate_info.rs
  rust/rti/src/in_transit_message_queue.rs
  rust/rti/src/lib.rs
  rust/rti/src/message_record/message_record.rs
  rust/rti/src/net_common.rs
  rust/rti/src/net_util.rs
  rust/rti/src/rti_common.rs
  rust/rti/src/rti_remote.rs
  rust/rti/src/server.rs
  rust/rti/src/tag.rs
Labels: testing

#49 Enable clock synchronization with federates
  rust/rti/src/federate_info.rs
  rust/rti/src/lib.rs
  rust/rti/src/net_common.rs
  rust/rti/src/net_util.rs
  rust/rti/src/rti_remote.rs
  rust/rti/src/server.rs
Labels: ready
